FROM node:20-alpine as build-stage

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

ARG VITE_API_URL=/api
ARG VITE_SUPPORT_WHATSAPP_NUMBER

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SUPPORT_WHATSAPP_NUMBER=$VITE_SUPPORT_WHATSAPP_NUMBER

RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5273

CMD ["nginx", "-g", "daemon off;"]
