FROM node:20-alpine as build-stage

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

ENV VITE_API_URL=/api

RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]
